theme: jekyll-theme-minimal

# theme: jekyll-theme-minimal
# title: 
# description: Computer Science Graduate Student | Machine Learning | Privacy Protection
# logo: /assets/img/your_photo.jpg
# show_downloads: false
# google_analytics: [Your tracking ID]